// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"pentag.kr/distimer/ent/apnstoken"
	"pentag.kr/distimer/ent/predicate"
	"pentag.kr/distimer/ent/session"
)

// APNsTokenQuery is the builder for querying APNsToken entities.
type APNsTokenQuery struct {
	config
	ctx         *QueryContext
	order       []apnstoken.OrderOption
	inters      []Interceptor
	predicates  []predicate.APNsToken
	withSession *SessionQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the APNsTokenQuery builder.
func (antq *APNsTokenQuery) Where(ps ...predicate.APNsToken) *APNsTokenQuery {
	antq.predicates = append(antq.predicates, ps...)
	return antq
}

// Limit the number of records to be returned by this query.
func (antq *APNsTokenQuery) Limit(limit int) *APNsTokenQuery {
	antq.ctx.Limit = &limit
	return antq
}

// Offset to start from.
func (antq *APNsTokenQuery) Offset(offset int) *APNsTokenQuery {
	antq.ctx.Offset = &offset
	return antq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (antq *APNsTokenQuery) Unique(unique bool) *APNsTokenQuery {
	antq.ctx.Unique = &unique
	return antq
}

// Order specifies how the records should be ordered.
func (antq *APNsTokenQuery) Order(o ...apnstoken.OrderOption) *APNsTokenQuery {
	antq.order = append(antq.order, o...)
	return antq
}

// QuerySession chains the current query on the "session" edge.
func (antq *APNsTokenQuery) QuerySession() *SessionQuery {
	query := (&SessionClient{config: antq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := antq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := antq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(apnstoken.Table, apnstoken.FieldID, selector),
			sqlgraph.To(session.Table, session.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, apnstoken.SessionTable, apnstoken.SessionColumn),
		)
		fromU = sqlgraph.SetNeighbors(antq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first APNsToken entity from the query.
// Returns a *NotFoundError when no APNsToken was found.
func (antq *APNsTokenQuery) First(ctx context.Context) (*APNsToken, error) {
	nodes, err := antq.Limit(1).All(setContextOp(ctx, antq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{apnstoken.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (antq *APNsTokenQuery) FirstX(ctx context.Context) *APNsToken {
	node, err := antq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first APNsToken ID from the query.
// Returns a *NotFoundError when no APNsToken ID was found.
func (antq *APNsTokenQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = antq.Limit(1).IDs(setContextOp(ctx, antq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{apnstoken.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (antq *APNsTokenQuery) FirstIDX(ctx context.Context) int {
	id, err := antq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single APNsToken entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one APNsToken entity is found.
// Returns a *NotFoundError when no APNsToken entities are found.
func (antq *APNsTokenQuery) Only(ctx context.Context) (*APNsToken, error) {
	nodes, err := antq.Limit(2).All(setContextOp(ctx, antq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{apnstoken.Label}
	default:
		return nil, &NotSingularError{apnstoken.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (antq *APNsTokenQuery) OnlyX(ctx context.Context) *APNsToken {
	node, err := antq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only APNsToken ID in the query.
// Returns a *NotSingularError when more than one APNsToken ID is found.
// Returns a *NotFoundError when no entities are found.
func (antq *APNsTokenQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = antq.Limit(2).IDs(setContextOp(ctx, antq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{apnstoken.Label}
	default:
		err = &NotSingularError{apnstoken.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (antq *APNsTokenQuery) OnlyIDX(ctx context.Context) int {
	id, err := antq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of APNsTokens.
func (antq *APNsTokenQuery) All(ctx context.Context) ([]*APNsToken, error) {
	ctx = setContextOp(ctx, antq.ctx, "All")
	if err := antq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*APNsToken, *APNsTokenQuery]()
	return withInterceptors[[]*APNsToken](ctx, antq, qr, antq.inters)
}

// AllX is like All, but panics if an error occurs.
func (antq *APNsTokenQuery) AllX(ctx context.Context) []*APNsToken {
	nodes, err := antq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of APNsToken IDs.
func (antq *APNsTokenQuery) IDs(ctx context.Context) (ids []int, err error) {
	if antq.ctx.Unique == nil && antq.path != nil {
		antq.Unique(true)
	}
	ctx = setContextOp(ctx, antq.ctx, "IDs")
	if err = antq.Select(apnstoken.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (antq *APNsTokenQuery) IDsX(ctx context.Context) []int {
	ids, err := antq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (antq *APNsTokenQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, antq.ctx, "Count")
	if err := antq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, antq, querierCount[*APNsTokenQuery](), antq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (antq *APNsTokenQuery) CountX(ctx context.Context) int {
	count, err := antq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (antq *APNsTokenQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, antq.ctx, "Exist")
	switch _, err := antq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (antq *APNsTokenQuery) ExistX(ctx context.Context) bool {
	exist, err := antq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the APNsTokenQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (antq *APNsTokenQuery) Clone() *APNsTokenQuery {
	if antq == nil {
		return nil
	}
	return &APNsTokenQuery{
		config:      antq.config,
		ctx:         antq.ctx.Clone(),
		order:       append([]apnstoken.OrderOption{}, antq.order...),
		inters:      append([]Interceptor{}, antq.inters...),
		predicates:  append([]predicate.APNsToken{}, antq.predicates...),
		withSession: antq.withSession.Clone(),
		// clone intermediate query.
		sql:  antq.sql.Clone(),
		path: antq.path,
	}
}

// WithSession tells the query-builder to eager-load the nodes that are connected to
// the "session" edge. The optional arguments are used to configure the query builder of the edge.
func (antq *APNsTokenQuery) WithSession(opts ...func(*SessionQuery)) *APNsTokenQuery {
	query := (&SessionClient{config: antq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	antq.withSession = query
	return antq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		StartToken string `json:"start_token,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.APNsToken.Query().
//		GroupBy(apnstoken.FieldStartToken).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (antq *APNsTokenQuery) GroupBy(field string, fields ...string) *APNsTokenGroupBy {
	antq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &APNsTokenGroupBy{build: antq}
	grbuild.flds = &antq.ctx.Fields
	grbuild.label = apnstoken.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		StartToken string `json:"start_token,omitempty"`
//	}
//
//	client.APNsToken.Query().
//		Select(apnstoken.FieldStartToken).
//		Scan(ctx, &v)
func (antq *APNsTokenQuery) Select(fields ...string) *APNsTokenSelect {
	antq.ctx.Fields = append(antq.ctx.Fields, fields...)
	sbuild := &APNsTokenSelect{APNsTokenQuery: antq}
	sbuild.label = apnstoken.Label
	sbuild.flds, sbuild.scan = &antq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a APNsTokenSelect configured with the given aggregations.
func (antq *APNsTokenQuery) Aggregate(fns ...AggregateFunc) *APNsTokenSelect {
	return antq.Select().Aggregate(fns...)
}

func (antq *APNsTokenQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range antq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, antq); err != nil {
				return err
			}
		}
	}
	for _, f := range antq.ctx.Fields {
		if !apnstoken.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if antq.path != nil {
		prev, err := antq.path(ctx)
		if err != nil {
			return err
		}
		antq.sql = prev
	}
	return nil
}

func (antq *APNsTokenQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*APNsToken, error) {
	var (
		nodes       = []*APNsToken{}
		withFKs     = antq.withFKs
		_spec       = antq.querySpec()
		loadedTypes = [1]bool{
			antq.withSession != nil,
		}
	)
	if antq.withSession != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, apnstoken.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*APNsToken).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &APNsToken{config: antq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, antq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := antq.withSession; query != nil {
		if err := antq.loadSession(ctx, query, nodes, nil,
			func(n *APNsToken, e *Session) { n.Edges.Session = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (antq *APNsTokenQuery) loadSession(ctx context.Context, query *SessionQuery, nodes []*APNsToken, init func(*APNsToken), assign func(*APNsToken, *Session)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*APNsToken)
	for i := range nodes {
		if nodes[i].session_apns_token == nil {
			continue
		}
		fk := *nodes[i].session_apns_token
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(session.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "session_apns_token" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (antq *APNsTokenQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := antq.querySpec()
	_spec.Node.Columns = antq.ctx.Fields
	if len(antq.ctx.Fields) > 0 {
		_spec.Unique = antq.ctx.Unique != nil && *antq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, antq.driver, _spec)
}

func (antq *APNsTokenQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(apnstoken.Table, apnstoken.Columns, sqlgraph.NewFieldSpec(apnstoken.FieldID, field.TypeInt))
	_spec.From = antq.sql
	if unique := antq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if antq.path != nil {
		_spec.Unique = true
	}
	if fields := antq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apnstoken.FieldID)
		for i := range fields {
			if fields[i] != apnstoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := antq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := antq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := antq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := antq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (antq *APNsTokenQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(antq.driver.Dialect())
	t1 := builder.Table(apnstoken.Table)
	columns := antq.ctx.Fields
	if len(columns) == 0 {
		columns = apnstoken.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if antq.sql != nil {
		selector = antq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if antq.ctx.Unique != nil && *antq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range antq.predicates {
		p(selector)
	}
	for _, p := range antq.order {
		p(selector)
	}
	if offset := antq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := antq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// APNsTokenGroupBy is the group-by builder for APNsToken entities.
type APNsTokenGroupBy struct {
	selector
	build *APNsTokenQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (antgb *APNsTokenGroupBy) Aggregate(fns ...AggregateFunc) *APNsTokenGroupBy {
	antgb.fns = append(antgb.fns, fns...)
	return antgb
}

// Scan applies the selector query and scans the result into the given value.
func (antgb *APNsTokenGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, antgb.build.ctx, "GroupBy")
	if err := antgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*APNsTokenQuery, *APNsTokenGroupBy](ctx, antgb.build, antgb, antgb.build.inters, v)
}

func (antgb *APNsTokenGroupBy) sqlScan(ctx context.Context, root *APNsTokenQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(antgb.fns))
	for _, fn := range antgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*antgb.flds)+len(antgb.fns))
		for _, f := range *antgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*antgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := antgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// APNsTokenSelect is the builder for selecting fields of APNsToken entities.
type APNsTokenSelect struct {
	*APNsTokenQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ants *APNsTokenSelect) Aggregate(fns ...AggregateFunc) *APNsTokenSelect {
	ants.fns = append(ants.fns, fns...)
	return ants
}

// Scan applies the selector query and scans the result into the given value.
func (ants *APNsTokenSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ants.ctx, "Select")
	if err := ants.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*APNsTokenQuery, *APNsTokenSelect](ctx, ants.APNsTokenQuery, ants, ants.inters, v)
}

func (ants *APNsTokenSelect) sqlScan(ctx context.Context, root *APNsTokenQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ants.fns))
	for _, fn := range ants.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ants.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ants.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
