// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"pentag.kr/distimer/ent/deleteduser"
	"pentag.kr/distimer/ent/predicate"
)

// DeletedUserQuery is the builder for querying DeletedUser entities.
type DeletedUserQuery struct {
	config
	ctx        *QueryContext
	order      []deleteduser.OrderOption
	inters     []Interceptor
	predicates []predicate.DeletedUser
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DeletedUserQuery builder.
func (duq *DeletedUserQuery) Where(ps ...predicate.DeletedUser) *DeletedUserQuery {
	duq.predicates = append(duq.predicates, ps...)
	return duq
}

// Limit the number of records to be returned by this query.
func (duq *DeletedUserQuery) Limit(limit int) *DeletedUserQuery {
	duq.ctx.Limit = &limit
	return duq
}

// Offset to start from.
func (duq *DeletedUserQuery) Offset(offset int) *DeletedUserQuery {
	duq.ctx.Offset = &offset
	return duq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (duq *DeletedUserQuery) Unique(unique bool) *DeletedUserQuery {
	duq.ctx.Unique = &unique
	return duq
}

// Order specifies how the records should be ordered.
func (duq *DeletedUserQuery) Order(o ...deleteduser.OrderOption) *DeletedUserQuery {
	duq.order = append(duq.order, o...)
	return duq
}

// First returns the first DeletedUser entity from the query.
// Returns a *NotFoundError when no DeletedUser was found.
func (duq *DeletedUserQuery) First(ctx context.Context) (*DeletedUser, error) {
	nodes, err := duq.Limit(1).All(setContextOp(ctx, duq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{deleteduser.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (duq *DeletedUserQuery) FirstX(ctx context.Context) *DeletedUser {
	node, err := duq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DeletedUser ID from the query.
// Returns a *NotFoundError when no DeletedUser ID was found.
func (duq *DeletedUserQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = duq.Limit(1).IDs(setContextOp(ctx, duq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{deleteduser.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (duq *DeletedUserQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := duq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DeletedUser entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DeletedUser entity is found.
// Returns a *NotFoundError when no DeletedUser entities are found.
func (duq *DeletedUserQuery) Only(ctx context.Context) (*DeletedUser, error) {
	nodes, err := duq.Limit(2).All(setContextOp(ctx, duq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{deleteduser.Label}
	default:
		return nil, &NotSingularError{deleteduser.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (duq *DeletedUserQuery) OnlyX(ctx context.Context) *DeletedUser {
	node, err := duq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DeletedUser ID in the query.
// Returns a *NotSingularError when more than one DeletedUser ID is found.
// Returns a *NotFoundError when no entities are found.
func (duq *DeletedUserQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = duq.Limit(2).IDs(setContextOp(ctx, duq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{deleteduser.Label}
	default:
		err = &NotSingularError{deleteduser.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (duq *DeletedUserQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := duq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DeletedUsers.
func (duq *DeletedUserQuery) All(ctx context.Context) ([]*DeletedUser, error) {
	ctx = setContextOp(ctx, duq.ctx, "All")
	if err := duq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DeletedUser, *DeletedUserQuery]()
	return withInterceptors[[]*DeletedUser](ctx, duq, qr, duq.inters)
}

// AllX is like All, but panics if an error occurs.
func (duq *DeletedUserQuery) AllX(ctx context.Context) []*DeletedUser {
	nodes, err := duq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DeletedUser IDs.
func (duq *DeletedUserQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if duq.ctx.Unique == nil && duq.path != nil {
		duq.Unique(true)
	}
	ctx = setContextOp(ctx, duq.ctx, "IDs")
	if err = duq.Select(deleteduser.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (duq *DeletedUserQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := duq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (duq *DeletedUserQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, duq.ctx, "Count")
	if err := duq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, duq, querierCount[*DeletedUserQuery](), duq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (duq *DeletedUserQuery) CountX(ctx context.Context) int {
	count, err := duq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (duq *DeletedUserQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, duq.ctx, "Exist")
	switch _, err := duq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (duq *DeletedUserQuery) ExistX(ctx context.Context) bool {
	exist, err := duq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DeletedUserQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (duq *DeletedUserQuery) Clone() *DeletedUserQuery {
	if duq == nil {
		return nil
	}
	return &DeletedUserQuery{
		config:     duq.config,
		ctx:        duq.ctx.Clone(),
		order:      append([]deleteduser.OrderOption{}, duq.order...),
		inters:     append([]Interceptor{}, duq.inters...),
		predicates: append([]predicate.DeletedUser{}, duq.predicates...),
		// clone intermediate query.
		sql:  duq.sql.Clone(),
		path: duq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DeletedUser.Query().
//		GroupBy(deleteduser.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (duq *DeletedUserQuery) GroupBy(field string, fields ...string) *DeletedUserGroupBy {
	duq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DeletedUserGroupBy{build: duq}
	grbuild.flds = &duq.ctx.Fields
	grbuild.label = deleteduser.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.DeletedUser.Query().
//		Select(deleteduser.FieldName).
//		Scan(ctx, &v)
func (duq *DeletedUserQuery) Select(fields ...string) *DeletedUserSelect {
	duq.ctx.Fields = append(duq.ctx.Fields, fields...)
	sbuild := &DeletedUserSelect{DeletedUserQuery: duq}
	sbuild.label = deleteduser.Label
	sbuild.flds, sbuild.scan = &duq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DeletedUserSelect configured with the given aggregations.
func (duq *DeletedUserQuery) Aggregate(fns ...AggregateFunc) *DeletedUserSelect {
	return duq.Select().Aggregate(fns...)
}

func (duq *DeletedUserQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range duq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, duq); err != nil {
				return err
			}
		}
	}
	for _, f := range duq.ctx.Fields {
		if !deleteduser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if duq.path != nil {
		prev, err := duq.path(ctx)
		if err != nil {
			return err
		}
		duq.sql = prev
	}
	return nil
}

func (duq *DeletedUserQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DeletedUser, error) {
	var (
		nodes = []*DeletedUser{}
		_spec = duq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DeletedUser).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DeletedUser{config: duq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, duq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (duq *DeletedUserQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := duq.querySpec()
	_spec.Node.Columns = duq.ctx.Fields
	if len(duq.ctx.Fields) > 0 {
		_spec.Unique = duq.ctx.Unique != nil && *duq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, duq.driver, _spec)
}

func (duq *DeletedUserQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(deleteduser.Table, deleteduser.Columns, sqlgraph.NewFieldSpec(deleteduser.FieldID, field.TypeUUID))
	_spec.From = duq.sql
	if unique := duq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if duq.path != nil {
		_spec.Unique = true
	}
	if fields := duq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deleteduser.FieldID)
		for i := range fields {
			if fields[i] != deleteduser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := duq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := duq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := duq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := duq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (duq *DeletedUserQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(duq.driver.Dialect())
	t1 := builder.Table(deleteduser.Table)
	columns := duq.ctx.Fields
	if len(columns) == 0 {
		columns = deleteduser.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if duq.sql != nil {
		selector = duq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if duq.ctx.Unique != nil && *duq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range duq.predicates {
		p(selector)
	}
	for _, p := range duq.order {
		p(selector)
	}
	if offset := duq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := duq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DeletedUserGroupBy is the group-by builder for DeletedUser entities.
type DeletedUserGroupBy struct {
	selector
	build *DeletedUserQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dugb *DeletedUserGroupBy) Aggregate(fns ...AggregateFunc) *DeletedUserGroupBy {
	dugb.fns = append(dugb.fns, fns...)
	return dugb
}

// Scan applies the selector query and scans the result into the given value.
func (dugb *DeletedUserGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dugb.build.ctx, "GroupBy")
	if err := dugb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeletedUserQuery, *DeletedUserGroupBy](ctx, dugb.build, dugb, dugb.build.inters, v)
}

func (dugb *DeletedUserGroupBy) sqlScan(ctx context.Context, root *DeletedUserQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(dugb.fns))
	for _, fn := range dugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*dugb.flds)+len(dugb.fns))
		for _, f := range *dugb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*dugb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dugb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DeletedUserSelect is the builder for selecting fields of DeletedUser entities.
type DeletedUserSelect struct {
	*DeletedUserQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (dus *DeletedUserSelect) Aggregate(fns ...AggregateFunc) *DeletedUserSelect {
	dus.fns = append(dus.fns, fns...)
	return dus
}

// Scan applies the selector query and scans the result into the given value.
func (dus *DeletedUserSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dus.ctx, "Select")
	if err := dus.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeletedUserQuery, *DeletedUserSelect](ctx, dus.DeletedUserQuery, dus, dus.inters, v)
}

func (dus *DeletedUserSelect) sqlScan(ctx context.Context, root *DeletedUserQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(dus.fns))
	for _, fn := range dus.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*dus.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
