// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"pentag.kr/distimer/ent/fcmtoken"
	"pentag.kr/distimer/ent/predicate"
)

// FCMTokenDelete is the builder for deleting a FCMToken entity.
type FCMTokenDelete struct {
	config
	hooks    []Hook
	mutation *FCMTokenMutation
}

// Where appends a list predicates to the FCMTokenDelete builder.
func (ftd *FCMTokenDelete) Where(ps ...predicate.FCMToken) *FCMTokenDelete {
	ftd.mutation.Where(ps...)
	return ftd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ftd *FCMTokenDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ftd.sqlExec, ftd.mutation, ftd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ftd *FCMTokenDelete) ExecX(ctx context.Context) int {
	n, err := ftd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ftd *FCMTokenDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(fcmtoken.Table, sqlgraph.NewFieldSpec(fcmtoken.FieldID, field.TypeInt))
	if ps := ftd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ftd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ftd.mutation.done = true
	return affected, err
}

// FCMTokenDeleteOne is the builder for deleting a single FCMToken entity.
type FCMTokenDeleteOne struct {
	ftd *FCMTokenDelete
}

// Where appends a list predicates to the FCMTokenDelete builder.
func (ftdo *FCMTokenDeleteOne) Where(ps ...predicate.FCMToken) *FCMTokenDeleteOne {
	ftdo.ftd.mutation.Where(ps...)
	return ftdo
}

// Exec executes the deletion query.
func (ftdo *FCMTokenDeleteOne) Exec(ctx context.Context) error {
	n, err := ftdo.ftd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{fcmtoken.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ftdo *FCMTokenDeleteOne) ExecX(ctx context.Context) {
	if err := ftdo.Exec(ctx); err != nil {
		panic(err)
	}
}
