// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"pentag.kr/distimer/ent/fcmtoken"
	"pentag.kr/distimer/ent/predicate"
	"pentag.kr/distimer/ent/session"
)

// FCMTokenQuery is the builder for querying FCMToken entities.
type FCMTokenQuery struct {
	config
	ctx         *QueryContext
	order       []fcmtoken.OrderOption
	inters      []Interceptor
	predicates  []predicate.FCMToken
	withSession *SessionQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FCMTokenQuery builder.
func (ftq *FCMTokenQuery) Where(ps ...predicate.FCMToken) *FCMTokenQuery {
	ftq.predicates = append(ftq.predicates, ps...)
	return ftq
}

// Limit the number of records to be returned by this query.
func (ftq *FCMTokenQuery) Limit(limit int) *FCMTokenQuery {
	ftq.ctx.Limit = &limit
	return ftq
}

// Offset to start from.
func (ftq *FCMTokenQuery) Offset(offset int) *FCMTokenQuery {
	ftq.ctx.Offset = &offset
	return ftq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ftq *FCMTokenQuery) Unique(unique bool) *FCMTokenQuery {
	ftq.ctx.Unique = &unique
	return ftq
}

// Order specifies how the records should be ordered.
func (ftq *FCMTokenQuery) Order(o ...fcmtoken.OrderOption) *FCMTokenQuery {
	ftq.order = append(ftq.order, o...)
	return ftq
}

// QuerySession chains the current query on the "session" edge.
func (ftq *FCMTokenQuery) QuerySession() *SessionQuery {
	query := (&SessionClient{config: ftq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ftq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ftq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(fcmtoken.Table, fcmtoken.FieldID, selector),
			sqlgraph.To(session.Table, session.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, fcmtoken.SessionTable, fcmtoken.SessionColumn),
		)
		fromU = sqlgraph.SetNeighbors(ftq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first FCMToken entity from the query.
// Returns a *NotFoundError when no FCMToken was found.
func (ftq *FCMTokenQuery) First(ctx context.Context) (*FCMToken, error) {
	nodes, err := ftq.Limit(1).All(setContextOp(ctx, ftq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{fcmtoken.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ftq *FCMTokenQuery) FirstX(ctx context.Context) *FCMToken {
	node, err := ftq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FCMToken ID from the query.
// Returns a *NotFoundError when no FCMToken ID was found.
func (ftq *FCMTokenQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ftq.Limit(1).IDs(setContextOp(ctx, ftq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{fcmtoken.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ftq *FCMTokenQuery) FirstIDX(ctx context.Context) int {
	id, err := ftq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FCMToken entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FCMToken entity is found.
// Returns a *NotFoundError when no FCMToken entities are found.
func (ftq *FCMTokenQuery) Only(ctx context.Context) (*FCMToken, error) {
	nodes, err := ftq.Limit(2).All(setContextOp(ctx, ftq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{fcmtoken.Label}
	default:
		return nil, &NotSingularError{fcmtoken.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ftq *FCMTokenQuery) OnlyX(ctx context.Context) *FCMToken {
	node, err := ftq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FCMToken ID in the query.
// Returns a *NotSingularError when more than one FCMToken ID is found.
// Returns a *NotFoundError when no entities are found.
func (ftq *FCMTokenQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ftq.Limit(2).IDs(setContextOp(ctx, ftq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{fcmtoken.Label}
	default:
		err = &NotSingularError{fcmtoken.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ftq *FCMTokenQuery) OnlyIDX(ctx context.Context) int {
	id, err := ftq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FCMTokens.
func (ftq *FCMTokenQuery) All(ctx context.Context) ([]*FCMToken, error) {
	ctx = setContextOp(ctx, ftq.ctx, "All")
	if err := ftq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FCMToken, *FCMTokenQuery]()
	return withInterceptors[[]*FCMToken](ctx, ftq, qr, ftq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ftq *FCMTokenQuery) AllX(ctx context.Context) []*FCMToken {
	nodes, err := ftq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FCMToken IDs.
func (ftq *FCMTokenQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ftq.ctx.Unique == nil && ftq.path != nil {
		ftq.Unique(true)
	}
	ctx = setContextOp(ctx, ftq.ctx, "IDs")
	if err = ftq.Select(fcmtoken.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ftq *FCMTokenQuery) IDsX(ctx context.Context) []int {
	ids, err := ftq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ftq *FCMTokenQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ftq.ctx, "Count")
	if err := ftq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ftq, querierCount[*FCMTokenQuery](), ftq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ftq *FCMTokenQuery) CountX(ctx context.Context) int {
	count, err := ftq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ftq *FCMTokenQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ftq.ctx, "Exist")
	switch _, err := ftq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ftq *FCMTokenQuery) ExistX(ctx context.Context) bool {
	exist, err := ftq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FCMTokenQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ftq *FCMTokenQuery) Clone() *FCMTokenQuery {
	if ftq == nil {
		return nil
	}
	return &FCMTokenQuery{
		config:      ftq.config,
		ctx:         ftq.ctx.Clone(),
		order:       append([]fcmtoken.OrderOption{}, ftq.order...),
		inters:      append([]Interceptor{}, ftq.inters...),
		predicates:  append([]predicate.FCMToken{}, ftq.predicates...),
		withSession: ftq.withSession.Clone(),
		// clone intermediate query.
		sql:  ftq.sql.Clone(),
		path: ftq.path,
	}
}

// WithSession tells the query-builder to eager-load the nodes that are connected to
// the "session" edge. The optional arguments are used to configure the query builder of the edge.
func (ftq *FCMTokenQuery) WithSession(opts ...func(*SessionQuery)) *FCMTokenQuery {
	query := (&SessionClient{config: ftq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ftq.withSession = query
	return ftq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PushToken string `json:"push_token,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FCMToken.Query().
//		GroupBy(fcmtoken.FieldPushToken).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ftq *FCMTokenQuery) GroupBy(field string, fields ...string) *FCMTokenGroupBy {
	ftq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FCMTokenGroupBy{build: ftq}
	grbuild.flds = &ftq.ctx.Fields
	grbuild.label = fcmtoken.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PushToken string `json:"push_token,omitempty"`
//	}
//
//	client.FCMToken.Query().
//		Select(fcmtoken.FieldPushToken).
//		Scan(ctx, &v)
func (ftq *FCMTokenQuery) Select(fields ...string) *FCMTokenSelect {
	ftq.ctx.Fields = append(ftq.ctx.Fields, fields...)
	sbuild := &FCMTokenSelect{FCMTokenQuery: ftq}
	sbuild.label = fcmtoken.Label
	sbuild.flds, sbuild.scan = &ftq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FCMTokenSelect configured with the given aggregations.
func (ftq *FCMTokenQuery) Aggregate(fns ...AggregateFunc) *FCMTokenSelect {
	return ftq.Select().Aggregate(fns...)
}

func (ftq *FCMTokenQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ftq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ftq); err != nil {
				return err
			}
		}
	}
	for _, f := range ftq.ctx.Fields {
		if !fcmtoken.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ftq.path != nil {
		prev, err := ftq.path(ctx)
		if err != nil {
			return err
		}
		ftq.sql = prev
	}
	return nil
}

func (ftq *FCMTokenQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FCMToken, error) {
	var (
		nodes       = []*FCMToken{}
		withFKs     = ftq.withFKs
		_spec       = ftq.querySpec()
		loadedTypes = [1]bool{
			ftq.withSession != nil,
		}
	)
	if ftq.withSession != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, fcmtoken.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FCMToken).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FCMToken{config: ftq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ftq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ftq.withSession; query != nil {
		if err := ftq.loadSession(ctx, query, nodes, nil,
			func(n *FCMToken, e *Session) { n.Edges.Session = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ftq *FCMTokenQuery) loadSession(ctx context.Context, query *SessionQuery, nodes []*FCMToken, init func(*FCMToken), assign func(*FCMToken, *Session)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*FCMToken)
	for i := range nodes {
		if nodes[i].session_fcm_token == nil {
			continue
		}
		fk := *nodes[i].session_fcm_token
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(session.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "session_fcm_token" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ftq *FCMTokenQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ftq.querySpec()
	_spec.Node.Columns = ftq.ctx.Fields
	if len(ftq.ctx.Fields) > 0 {
		_spec.Unique = ftq.ctx.Unique != nil && *ftq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ftq.driver, _spec)
}

func (ftq *FCMTokenQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(fcmtoken.Table, fcmtoken.Columns, sqlgraph.NewFieldSpec(fcmtoken.FieldID, field.TypeInt))
	_spec.From = ftq.sql
	if unique := ftq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ftq.path != nil {
		_spec.Unique = true
	}
	if fields := ftq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fcmtoken.FieldID)
		for i := range fields {
			if fields[i] != fcmtoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ftq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ftq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ftq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ftq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ftq *FCMTokenQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ftq.driver.Dialect())
	t1 := builder.Table(fcmtoken.Table)
	columns := ftq.ctx.Fields
	if len(columns) == 0 {
		columns = fcmtoken.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ftq.sql != nil {
		selector = ftq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ftq.ctx.Unique != nil && *ftq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ftq.predicates {
		p(selector)
	}
	for _, p := range ftq.order {
		p(selector)
	}
	if offset := ftq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ftq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FCMTokenGroupBy is the group-by builder for FCMToken entities.
type FCMTokenGroupBy struct {
	selector
	build *FCMTokenQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ftgb *FCMTokenGroupBy) Aggregate(fns ...AggregateFunc) *FCMTokenGroupBy {
	ftgb.fns = append(ftgb.fns, fns...)
	return ftgb
}

// Scan applies the selector query and scans the result into the given value.
func (ftgb *FCMTokenGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ftgb.build.ctx, "GroupBy")
	if err := ftgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FCMTokenQuery, *FCMTokenGroupBy](ctx, ftgb.build, ftgb, ftgb.build.inters, v)
}

func (ftgb *FCMTokenGroupBy) sqlScan(ctx context.Context, root *FCMTokenQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ftgb.fns))
	for _, fn := range ftgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ftgb.flds)+len(ftgb.fns))
		for _, f := range *ftgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ftgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ftgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FCMTokenSelect is the builder for selecting fields of FCMToken entities.
type FCMTokenSelect struct {
	*FCMTokenQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fts *FCMTokenSelect) Aggregate(fns ...AggregateFunc) *FCMTokenSelect {
	fts.fns = append(fts.fns, fns...)
	return fts
}

// Scan applies the selector query and scans the result into the given value.
func (fts *FCMTokenSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fts.ctx, "Select")
	if err := fts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FCMTokenQuery, *FCMTokenSelect](ctx, fts.FCMTokenQuery, fts, fts.inters, v)
}

func (fts *FCMTokenSelect) sqlScan(ctx context.Context, root *FCMTokenQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fts.fns))
	for _, fn := range fts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
