// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"pentag.kr/distimer/ent/group"
	"pentag.kr/distimer/ent/invitecode"
	"pentag.kr/distimer/ent/predicate"
)

// InviteCodeUpdate is the builder for updating InviteCode entities.
type InviteCodeUpdate struct {
	config
	hooks    []Hook
	mutation *InviteCodeMutation
}

// Where appends a list predicates to the InviteCodeUpdate builder.
func (icu *InviteCodeUpdate) Where(ps ...predicate.InviteCode) *InviteCodeUpdate {
	icu.mutation.Where(ps...)
	return icu
}

// SetCode sets the "code" field.
func (icu *InviteCodeUpdate) SetCode(s string) *InviteCodeUpdate {
	icu.mutation.SetCode(s)
	return icu
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (icu *InviteCodeUpdate) SetNillableCode(s *string) *InviteCodeUpdate {
	if s != nil {
		icu.SetCode(*s)
	}
	return icu
}

// SetUsed sets the "used" field.
func (icu *InviteCodeUpdate) SetUsed(b bool) *InviteCodeUpdate {
	icu.mutation.SetUsed(b)
	return icu
}

// SetNillableUsed sets the "used" field if the given value is not nil.
func (icu *InviteCodeUpdate) SetNillableUsed(b *bool) *InviteCodeUpdate {
	if b != nil {
		icu.SetUsed(*b)
	}
	return icu
}

// SetGroupID sets the "group" edge to the Group entity by ID.
func (icu *InviteCodeUpdate) SetGroupID(id uuid.UUID) *InviteCodeUpdate {
	icu.mutation.SetGroupID(id)
	return icu
}

// SetGroup sets the "group" edge to the Group entity.
func (icu *InviteCodeUpdate) SetGroup(g *Group) *InviteCodeUpdate {
	return icu.SetGroupID(g.ID)
}

// Mutation returns the InviteCodeMutation object of the builder.
func (icu *InviteCodeUpdate) Mutation() *InviteCodeMutation {
	return icu.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (icu *InviteCodeUpdate) ClearGroup() *InviteCodeUpdate {
	icu.mutation.ClearGroup()
	return icu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (icu *InviteCodeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, icu.sqlSave, icu.mutation, icu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (icu *InviteCodeUpdate) SaveX(ctx context.Context) int {
	affected, err := icu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (icu *InviteCodeUpdate) Exec(ctx context.Context) error {
	_, err := icu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (icu *InviteCodeUpdate) ExecX(ctx context.Context) {
	if err := icu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (icu *InviteCodeUpdate) check() error {
	if _, ok := icu.mutation.GroupID(); icu.mutation.GroupCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "InviteCode.group"`)
	}
	return nil
}

func (icu *InviteCodeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := icu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(invitecode.Table, invitecode.Columns, sqlgraph.NewFieldSpec(invitecode.FieldID, field.TypeInt))
	if ps := icu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := icu.mutation.Code(); ok {
		_spec.SetField(invitecode.FieldCode, field.TypeString, value)
	}
	if value, ok := icu.mutation.Used(); ok {
		_spec.SetField(invitecode.FieldUsed, field.TypeBool, value)
	}
	if icu.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitecode.GroupTable,
			Columns: []string{invitecode.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := icu.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitecode.GroupTable,
			Columns: []string{invitecode.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, icu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invitecode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	icu.mutation.done = true
	return n, nil
}

// InviteCodeUpdateOne is the builder for updating a single InviteCode entity.
type InviteCodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InviteCodeMutation
}

// SetCode sets the "code" field.
func (icuo *InviteCodeUpdateOne) SetCode(s string) *InviteCodeUpdateOne {
	icuo.mutation.SetCode(s)
	return icuo
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (icuo *InviteCodeUpdateOne) SetNillableCode(s *string) *InviteCodeUpdateOne {
	if s != nil {
		icuo.SetCode(*s)
	}
	return icuo
}

// SetUsed sets the "used" field.
func (icuo *InviteCodeUpdateOne) SetUsed(b bool) *InviteCodeUpdateOne {
	icuo.mutation.SetUsed(b)
	return icuo
}

// SetNillableUsed sets the "used" field if the given value is not nil.
func (icuo *InviteCodeUpdateOne) SetNillableUsed(b *bool) *InviteCodeUpdateOne {
	if b != nil {
		icuo.SetUsed(*b)
	}
	return icuo
}

// SetGroupID sets the "group" edge to the Group entity by ID.
func (icuo *InviteCodeUpdateOne) SetGroupID(id uuid.UUID) *InviteCodeUpdateOne {
	icuo.mutation.SetGroupID(id)
	return icuo
}

// SetGroup sets the "group" edge to the Group entity.
func (icuo *InviteCodeUpdateOne) SetGroup(g *Group) *InviteCodeUpdateOne {
	return icuo.SetGroupID(g.ID)
}

// Mutation returns the InviteCodeMutation object of the builder.
func (icuo *InviteCodeUpdateOne) Mutation() *InviteCodeMutation {
	return icuo.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (icuo *InviteCodeUpdateOne) ClearGroup() *InviteCodeUpdateOne {
	icuo.mutation.ClearGroup()
	return icuo
}

// Where appends a list predicates to the InviteCodeUpdate builder.
func (icuo *InviteCodeUpdateOne) Where(ps ...predicate.InviteCode) *InviteCodeUpdateOne {
	icuo.mutation.Where(ps...)
	return icuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (icuo *InviteCodeUpdateOne) Select(field string, fields ...string) *InviteCodeUpdateOne {
	icuo.fields = append([]string{field}, fields...)
	return icuo
}

// Save executes the query and returns the updated InviteCode entity.
func (icuo *InviteCodeUpdateOne) Save(ctx context.Context) (*InviteCode, error) {
	return withHooks(ctx, icuo.sqlSave, icuo.mutation, icuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (icuo *InviteCodeUpdateOne) SaveX(ctx context.Context) *InviteCode {
	node, err := icuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (icuo *InviteCodeUpdateOne) Exec(ctx context.Context) error {
	_, err := icuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (icuo *InviteCodeUpdateOne) ExecX(ctx context.Context) {
	if err := icuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (icuo *InviteCodeUpdateOne) check() error {
	if _, ok := icuo.mutation.GroupID(); icuo.mutation.GroupCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "InviteCode.group"`)
	}
	return nil
}

func (icuo *InviteCodeUpdateOne) sqlSave(ctx context.Context) (_node *InviteCode, err error) {
	if err := icuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invitecode.Table, invitecode.Columns, sqlgraph.NewFieldSpec(invitecode.FieldID, field.TypeInt))
	id, ok := icuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InviteCode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := icuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invitecode.FieldID)
		for _, f := range fields {
			if !invitecode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invitecode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := icuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := icuo.mutation.Code(); ok {
		_spec.SetField(invitecode.FieldCode, field.TypeString, value)
	}
	if value, ok := icuo.mutation.Used(); ok {
		_spec.SetField(invitecode.FieldUsed, field.TypeBool, value)
	}
	if icuo.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitecode.GroupTable,
			Columns: []string{invitecode.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := icuo.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitecode.GroupTable,
			Columns: []string{invitecode.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &InviteCode{config: icuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, icuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invitecode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	icuo.mutation.done = true
	return _node, nil
}
