// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"pentag.kr/distimer/ent/apnstoken"
	"pentag.kr/distimer/ent/fcmtoken"
	"pentag.kr/distimer/ent/predicate"
	"pentag.kr/distimer/ent/session"
	"pentag.kr/distimer/ent/user"
)

// SessionUpdate is the builder for updating Session entities.
type SessionUpdate struct {
	config
	hooks    []Hook
	mutation *SessionMutation
}

// Where appends a list predicates to the SessionUpdate builder.
func (su *SessionUpdate) Where(ps ...predicate.Session) *SessionUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetRefreshToken sets the "refresh_token" field.
func (su *SessionUpdate) SetRefreshToken(u uuid.UUID) *SessionUpdate {
	su.mutation.SetRefreshToken(u)
	return su
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (su *SessionUpdate) SetNillableRefreshToken(u *uuid.UUID) *SessionUpdate {
	if u != nil {
		su.SetRefreshToken(*u)
	}
	return su
}

// SetLastActive sets the "last_active" field.
func (su *SessionUpdate) SetLastActive(t time.Time) *SessionUpdate {
	su.mutation.SetLastActive(t)
	return su
}

// SetNillableLastActive sets the "last_active" field if the given value is not nil.
func (su *SessionUpdate) SetNillableLastActive(t *time.Time) *SessionUpdate {
	if t != nil {
		su.SetLastActive(*t)
	}
	return su
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (su *SessionUpdate) SetOwnerID(id uuid.UUID) *SessionUpdate {
	su.mutation.SetOwnerID(id)
	return su
}

// SetOwner sets the "owner" edge to the User entity.
func (su *SessionUpdate) SetOwner(u *User) *SessionUpdate {
	return su.SetOwnerID(u.ID)
}

// SetApnsTokenID sets the "apns_token" edge to the APNsToken entity by ID.
func (su *SessionUpdate) SetApnsTokenID(id int) *SessionUpdate {
	su.mutation.SetApnsTokenID(id)
	return su
}

// SetNillableApnsTokenID sets the "apns_token" edge to the APNsToken entity by ID if the given value is not nil.
func (su *SessionUpdate) SetNillableApnsTokenID(id *int) *SessionUpdate {
	if id != nil {
		su = su.SetApnsTokenID(*id)
	}
	return su
}

// SetApnsToken sets the "apns_token" edge to the APNsToken entity.
func (su *SessionUpdate) SetApnsToken(a *APNsToken) *SessionUpdate {
	return su.SetApnsTokenID(a.ID)
}

// SetFcmTokenID sets the "fcm_token" edge to the FCMToken entity by ID.
func (su *SessionUpdate) SetFcmTokenID(id int) *SessionUpdate {
	su.mutation.SetFcmTokenID(id)
	return su
}

// SetNillableFcmTokenID sets the "fcm_token" edge to the FCMToken entity by ID if the given value is not nil.
func (su *SessionUpdate) SetNillableFcmTokenID(id *int) *SessionUpdate {
	if id != nil {
		su = su.SetFcmTokenID(*id)
	}
	return su
}

// SetFcmToken sets the "fcm_token" edge to the FCMToken entity.
func (su *SessionUpdate) SetFcmToken(f *FCMToken) *SessionUpdate {
	return su.SetFcmTokenID(f.ID)
}

// Mutation returns the SessionMutation object of the builder.
func (su *SessionUpdate) Mutation() *SessionMutation {
	return su.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (su *SessionUpdate) ClearOwner() *SessionUpdate {
	su.mutation.ClearOwner()
	return su
}

// ClearApnsToken clears the "apns_token" edge to the APNsToken entity.
func (su *SessionUpdate) ClearApnsToken() *SessionUpdate {
	su.mutation.ClearApnsToken()
	return su
}

// ClearFcmToken clears the "fcm_token" edge to the FCMToken entity.
func (su *SessionUpdate) ClearFcmToken() *SessionUpdate {
	su.mutation.ClearFcmToken()
	return su
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SessionUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SessionUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SessionUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *SessionUpdate) check() error {
	if _, ok := su.mutation.OwnerID(); su.mutation.OwnerCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Session.owner"`)
	}
	return nil
}

func (su *SessionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.RefreshToken(); ok {
		_spec.SetField(session.FieldRefreshToken, field.TypeUUID, value)
	}
	if value, ok := su.mutation.LastActive(); ok {
		_spec.SetField(session.FieldLastActive, field.TypeTime, value)
	}
	if su.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.OwnerTable,
			Columns: []string{session.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.OwnerTable,
			Columns: []string{session.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.ApnsTokenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   session.ApnsTokenTable,
			Columns: []string{session.ApnsTokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apnstoken.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.ApnsTokenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   session.ApnsTokenTable,
			Columns: []string{session.ApnsTokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apnstoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.FcmTokenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   session.FcmTokenTable,
			Columns: []string{session.FcmTokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fcmtoken.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.FcmTokenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   session.FcmTokenTable,
			Columns: []string{session.FcmTokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fcmtoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SessionUpdateOne is the builder for updating a single Session entity.
type SessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SessionMutation
}

// SetRefreshToken sets the "refresh_token" field.
func (suo *SessionUpdateOne) SetRefreshToken(u uuid.UUID) *SessionUpdateOne {
	suo.mutation.SetRefreshToken(u)
	return suo
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (suo *SessionUpdateOne) SetNillableRefreshToken(u *uuid.UUID) *SessionUpdateOne {
	if u != nil {
		suo.SetRefreshToken(*u)
	}
	return suo
}

// SetLastActive sets the "last_active" field.
func (suo *SessionUpdateOne) SetLastActive(t time.Time) *SessionUpdateOne {
	suo.mutation.SetLastActive(t)
	return suo
}

// SetNillableLastActive sets the "last_active" field if the given value is not nil.
func (suo *SessionUpdateOne) SetNillableLastActive(t *time.Time) *SessionUpdateOne {
	if t != nil {
		suo.SetLastActive(*t)
	}
	return suo
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (suo *SessionUpdateOne) SetOwnerID(id uuid.UUID) *SessionUpdateOne {
	suo.mutation.SetOwnerID(id)
	return suo
}

// SetOwner sets the "owner" edge to the User entity.
func (suo *SessionUpdateOne) SetOwner(u *User) *SessionUpdateOne {
	return suo.SetOwnerID(u.ID)
}

// SetApnsTokenID sets the "apns_token" edge to the APNsToken entity by ID.
func (suo *SessionUpdateOne) SetApnsTokenID(id int) *SessionUpdateOne {
	suo.mutation.SetApnsTokenID(id)
	return suo
}

// SetNillableApnsTokenID sets the "apns_token" edge to the APNsToken entity by ID if the given value is not nil.
func (suo *SessionUpdateOne) SetNillableApnsTokenID(id *int) *SessionUpdateOne {
	if id != nil {
		suo = suo.SetApnsTokenID(*id)
	}
	return suo
}

// SetApnsToken sets the "apns_token" edge to the APNsToken entity.
func (suo *SessionUpdateOne) SetApnsToken(a *APNsToken) *SessionUpdateOne {
	return suo.SetApnsTokenID(a.ID)
}

// SetFcmTokenID sets the "fcm_token" edge to the FCMToken entity by ID.
func (suo *SessionUpdateOne) SetFcmTokenID(id int) *SessionUpdateOne {
	suo.mutation.SetFcmTokenID(id)
	return suo
}

// SetNillableFcmTokenID sets the "fcm_token" edge to the FCMToken entity by ID if the given value is not nil.
func (suo *SessionUpdateOne) SetNillableFcmTokenID(id *int) *SessionUpdateOne {
	if id != nil {
		suo = suo.SetFcmTokenID(*id)
	}
	return suo
}

// SetFcmToken sets the "fcm_token" edge to the FCMToken entity.
func (suo *SessionUpdateOne) SetFcmToken(f *FCMToken) *SessionUpdateOne {
	return suo.SetFcmTokenID(f.ID)
}

// Mutation returns the SessionMutation object of the builder.
func (suo *SessionUpdateOne) Mutation() *SessionMutation {
	return suo.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (suo *SessionUpdateOne) ClearOwner() *SessionUpdateOne {
	suo.mutation.ClearOwner()
	return suo
}

// ClearApnsToken clears the "apns_token" edge to the APNsToken entity.
func (suo *SessionUpdateOne) ClearApnsToken() *SessionUpdateOne {
	suo.mutation.ClearApnsToken()
	return suo
}

// ClearFcmToken clears the "fcm_token" edge to the FCMToken entity.
func (suo *SessionUpdateOne) ClearFcmToken() *SessionUpdateOne {
	suo.mutation.ClearFcmToken()
	return suo
}

// Where appends a list predicates to the SessionUpdate builder.
func (suo *SessionUpdateOne) Where(ps ...predicate.Session) *SessionUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SessionUpdateOne) Select(field string, fields ...string) *SessionUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Session entity.
func (suo *SessionUpdateOne) Save(ctx context.Context) (*Session, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SessionUpdateOne) SaveX(ctx context.Context) *Session {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SessionUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SessionUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *SessionUpdateOne) check() error {
	if _, ok := suo.mutation.OwnerID(); suo.mutation.OwnerCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Session.owner"`)
	}
	return nil
}

func (suo *SessionUpdateOne) sqlSave(ctx context.Context) (_node *Session, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Session.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, session.FieldID)
		for _, f := range fields {
			if !session.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != session.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.RefreshToken(); ok {
		_spec.SetField(session.FieldRefreshToken, field.TypeUUID, value)
	}
	if value, ok := suo.mutation.LastActive(); ok {
		_spec.SetField(session.FieldLastActive, field.TypeTime, value)
	}
	if suo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.OwnerTable,
			Columns: []string{session.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.OwnerTable,
			Columns: []string{session.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.ApnsTokenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   session.ApnsTokenTable,
			Columns: []string{session.ApnsTokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apnstoken.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.ApnsTokenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   session.ApnsTokenTable,
			Columns: []string{session.ApnsTokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apnstoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.FcmTokenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   session.FcmTokenTable,
			Columns: []string{session.FcmTokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fcmtoken.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.FcmTokenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   session.FcmTokenTable,
			Columns: []string{session.FcmTokenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fcmtoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Session{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
