// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// APNsToken is the predicate function for apnstoken builders.
type APNsToken func(*sql.Selector)

// Affiliation is the predicate function for affiliation builders.
type Affiliation func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// DeletedUser is the predicate function for deleteduser builders.
type DeletedUser func(*sql.Selector)

// FCMToken is the predicate function for fcmtoken builders.
type FCMToken func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// InviteCode is the predicate function for invitecode builders.
type InviteCode func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// StudyLog is the predicate function for studylog builders.
type StudyLog func(*sql.Selector)

// Subject is the predicate function for subject builders.
type Subject func(*sql.Selector)

// Timer is the predicate function for timer builders.
type Timer func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
